name: First workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: unbuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World"
      - name: printgood bye
        run: echo "Done -bye"
